# Generated by Django 5.0.1 on 2024-01-17 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_score_created_at_score_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='TotalScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('highest_level', models.IntegerField()),
                ('total_time', models.IntegerField()),
                ('total_money', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameField(
            model_name='score',
            old_name='energy_used',
            new_name='level',
        ),
        migrations.RenameField(
            model_name='score',
            old_name='level_completed',
            new_name='time',
        ),
    ]
